version: "~> 1.0"
os: linux
dist: xenial
language: python
python:
  - '3.6'
services:
  - docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: JaUUqkiKix+ZIk6Qz18y0anPb21zTYWiZwDjZ9u+EF3u5dtPjUC2pxZcePMFGz+Cs4h0+vMsEajRImE4ck9yEGsYtY1mqIMDUlT971/y0miAp0ZCuLNCFg/dYiWH8mT2ypt234l4afguB+tHPJHr9RHm7Ge55CvFSKKGUp8qoSqAEo9ZJdzvl8uULCR3g6nakAiZV8fqu+ue0SqTipxHxxGwHxivN/mCOU6APpr4VtfJ+MtJfhOwjVH8UTyXpOg6swi596V1GHK+Q1X0d0I99HcJaS8wK/X+vegOpPv/MTzbSnc1xsZ+irq2dsUJhVc5fKcjCW7Jk0gwpMUhmZmWUP7KMadcUJByeU+7HorAkdX8pVoOcd453RauhZr+q9Mv5qasEMvO+C3RUFy431lGmPwywZBdclB2LtXSXFAXEVp/d/nK3l7SNDPb6R/jFll6T+sWbNOG4UUz3TG5Mb4iiBIE/zKe3g9sz/mePnAMWgVNHWiCI2I2bFkBsmxBt8ceSCwCKx5CcTORAVGov39VQm0BDtzRnxfDprW7Qny4hJi5PjyeujaC4lDg59MUJ3WGp+paUiGFGk3EUDx/ijgp2UBsvOGzva6JornlBwd68QEeUEr81dq/lI87Wc4vvRhUKOpbTbhVGrqKcExqXFyCFPMx+VtcbT8mWvrUK99Y0IQ=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
install:
  - pip install -r requirements.txt
env:
  jobs:
    - SCENARIO=default
script:
  - molecule test --scenario-name ${SCENARIO}
